name: Run Automated Tests with Seeker

on: push

jobs:
  run-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
        
      # Run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: ./test
          start: java -jar target/api.jar
