name: Run Automated Tests with Seeker

on: push

jobs:
  run-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      
      - name: Copy build artifacts
        run: cp target/api.jar test/api.jar

      
      - uses: Sean18/SeekerAction@main
        with:
          base-url: https://seeker.field-test.blackduck.com
          project-key: 'hippotech_github'
          output-path: test/seeker-agent.jar

          
      # Run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./test
          start: java -javaagent:./seeker-agent.jar -jar api.jar
          wait-on: 'http://localhost:3001'
